# Generated by Django 3.0.5 on 2020-04-30 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userhome', '0002_user_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_history',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Category'),
        ),
    ]
