# Generated by Django 3.0.5 on 2020-04-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0003_auto_20200430_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_history',
            name='history',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
