# Generated by Django 3.0.5 on 2020-05-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0004_auto_20200430_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='videofile',
            field=models.ImageField(blank=True, upload_to='videos/'),
        ),
    ]
